### ISSUE TITLE
consider making fzy a library?

### ISSUE THREAD

**Issue by haolian9** [gpanders/fzy.zig#3]
hi, could you consider making fzy a library so that people (me) can include it into their project in source level?

i have made a [quick draft](https://github.com/haolian9/zd/blob/fzy/src/main.zig#L139) to use fzy in my project as a fuzzy matcher of directories, what i changed are:
* custom [launcher](https://github.com/haolian9/zd/blob/fzy/src/fzy/launch.zig): no cli args parsing is needed, so i removed the Options.new() and the dependency of clap
* config.h -> config.zig
* add a [OutputWriter field to TtyInterface](https://github.com/haolian9/zd/blob/fzy/src/fzy/TtyInterface.zig#L18), so that i can control where the result will be wrote to
* return code -> errors.*

that's quite some changes, but i'm still wondering how do you think about this usecase.

**Comment by gpanders** [comment]
If this is something that would be useful for you, then go for it. You can send me a PR if you like, or just maintain your own fork.

I did go ahead and convert config.h to config.zig, as that was already long overdue.

**Comment by haolian9** [comment]
thanks for your reply!
i will play with it on my side for now to see if it is possible and worth to contribute to upstream.
